### ISSUE TITLE
[S1 - PBI2] User/Guest dapat melihat artikel penyakit umum pada lansia beserta solusinya

### ISSUE THREAD

**Issue by NizurAdha** [SI-RPL-2022/SI4305_D_ELDERLYCAREGIVER#4]
Saya sebagai User dapat melihat artikel penyakit umum pada lansia beserta solusinya sehingga saya dapat mengetahui jenis penyakit pada lansia.

**Comment by mharitsah** [comment]
PBI telah selesai, issue ditutup

**Comment by NizurAdha** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/92109106/161710731-8db7419e-6e9d-41ae-849c-790598dd4349.png">
