### ISSUE TITLE
[S1 - PBI7] Administrator dapat melihat jumlah user yang ada

### ISSUE THREAD

**Issue by NizurAdha** [SI-RPL-2022/SI4305_D_ELDERLYCAREGIVER#5]
Saya sebagai Admin ingin melihat jumlah user yang ada sehingga saya dapat mengetahui berapa banyak user yang menggunakan web Elderly Caregiver.

**Comment by mharitsah** [comment]
PBI telah selesai, issue di tutup

**Comment by NizurAdha** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/92109106/161709509-cfb7bb7e-2698-4817-b1f6-0dfbfe9f1597.png">

**Comment by insouc** [comment]
issue dibuka kembali karena ada beberapa bagian yang harus direvisi oleh arfin dan rafi

**Comment by mharitsah** [comment]
Perbaikan redirect admin ke dashboard

![image](https://user-images.githubusercontent.com/70809383/161747891-be2ec4c6-1226-4c1a-8b44-0ff5a4db93c9.png)

**Comment by mharitsah** [comment]
PBI telah selesai, issue di tutup
