### ISSUE TITLE
[S1 - PBI3] Administrator dapat membuat artikel penyakit umum pada lansia beserta solusinya

### ISSUE THREAD

**Issue by mraihanh12** [SI-RPL-2022/SI4305_D_ELDERLYCAREGIVER#6]
Saya sebagai Admin ingin dapat membuat artikel penyakit umur pada lansia sehingga saya dapat memberikan informasi kepada user tentang penyakit umur pada lansia

**Comment by rafmul3** [comment]
test2

**Comment by mharitsah** [comment]
PBI telah selesai, issue ditutup
